### PR TITLE
update pypy version in CI workflow

### PR DESCRIPTION
**Pull request by om26er**
This should fix the CI (hopefully)

### CODE REVIEW

**Comment by om26er** [comment]
Looks like twisted in trunk requires Python 3.8 minimal. So either we disable CI to not run for twisted trunk when using 3.7 OR we upgrade the project to 3.8

**Comment by oberstet** [comment]
ahh, hi Omer;) and thanks for chiming in. as you say, we have 2 options. I'd go with "Python 3.8 minimal." or even CPython 3.9 minimal and whatever PyPy minimal this corresponds to. I have good experiences with 3.9 and it makes sense IMO rgd a minimal Python version (including distros I guess even though I am usually running from vanilla sources ..). also, I would definitely want to track Twisted trunk since it is such an essential pieces, also because of txaio downstream projects like Crossbar.io which require tx rather than aio ..

**Comment by om26er** [comment]
hey Tobias, I tried to update a few deps, its still failing. Will find a proper fix later tonight and update this PR

**Comment by oberstet** [comment]
first, yes, thanks!

then, oh well:( there seems to be yet another CI issue. I don't have time to look into ..

third, fwiw, I am running this python these days regularily:

```
(.venv) oberstet@intel-nuci7:~/scm/typedefint/rfminer$ python -V
Python 3.12.1
```

thus, we might add CPython 3.12 in testing

finally, I recently stumbled across

https://devclass.com/2024/01/10/just-in-time-compiler-likely-to-arrive-in-python-3-13/

so PyPy is going to get some competition? ;) I have not yet done any testing, or even performance testing / comparison with PyPy

and then: PyPy not only has JIT, but incremental GC, which is essential for real-world performance eg in Crossbar.io. so I am not holding my breath;)

**Comment by oberstet** [comment]
cool, thanks a lot!!

one more note:

we should also update https://github.com/crossbario/txaio/blob/50a111a95b19168127681429bebd3827e1e2f6e5/setup.py#L105

fwiw, _if_ required, I don't have a problem bumping min versions of deps https://github.com/crossbario/txaio/blob/master/requirements.txt .. if required ..

**Comment by om26er** [comment]
One of the test failures is caused by a regression in the upstream code. I have notified the upstream https://github.com/twisted/twisted/pull/12040#issuecomment-1888181534

**Comment by oberstet** [comment]
Hi Omer, thank you so much! I mean, both for figuring it out, and for stepping up within Twisted, moving things forward! this is awesome. even though it is a Twisted regression, and the fallout is hitting us within Autobahn etc, this even more so kinda supports what I said with keeping Twisted trunk in the CI here: we would not even know what's coming down the road and will affect us later if we wouldn't include tx trunk, and we would not be able to provide early feedback to Twisted upstream, and that obviously wouldn't be helpful for anyone, neither "us" nor "them" as in Twisted, and it wouldn't be true OSS good citizenship. Anyways, I'm sure you tick the same;) Again, thank you for contributing and helping!

**Comment by om26er** [comment]
@oberstet looks like CI is all good now

**Comment by om26er** [comment]
In a follow up PR, we may want to update Python 3.11 to 3.12 instead as that's the latest stable now

**Comment by oberstet** [comment]
fyi, reconfigured required CI for

grafik

---

> In a follow up PR, we may want to update Python 3.11 to 3.12 instead as that's the latest stable now

yep, +1! I think this would make sense, we have CPython 3.9 + 3.12, and PyPy 3.9 and 3.10, and tx trunk and releases. this would give us "look back" and "look forward" visibility into any issues ..

**Comment by oberstet** [comment]
another note, I just wanted to disable (but not delete) the "deploy" action, and that worked previously in GH actions (I could disable individual actions via web UI before), but it doesn't seem to work/be available anymore -- or I am too dumb to find it;)

grafik

**Pull request merged**
