### PR TITLE
add wall-time helpers

### PR DESCRIPTION
**Pull request by om26er**

### CODE REVIEW

**Comment by oberstet** [comment]
# py34-twtrunk

fails with

```
Twisted requires Python '>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*' but the running Python is 3.4.8
```

which is expected since we use python 3.4 here, but install twisted version open-ended - and twisted has ceased to support py < 3.5

# coverage

coverage errors .. in a whole bunch of the other failing tests:

```
ERROR: InvocationError for command /home/travis/build/crossbario/txaio/.tox/py35-twtrunk/bin/coverage run --parallel-mode --source=txaio /home/travis/build/crossbario/txaio/.tox/py35-twtrunk/bin/py.test -v -s --basetemp=/home/travis/build/crossbario/txaio/.tox/py35-twtrunk/tmp (exited with code 1)

___________________________________ summary ____________________________________

ERROR:   py35-twtrunk: commands failed

The command "tox -c tox.ini -e $TOX_ENV" exited with 1.
```

not sure why .. but this more likely seems unrelated. lets see what your CI trigger PR results in ..

**Comment by om26er** [comment]
> not sure why .. but this more likely seems unrelated. lets see what your CI trigger PR results in ..

yeah, the failure seems unrelated, not sure why does the CI not show any useful logs there

**Comment by om26er** [comment]
Once this PR lands, it might be the time to do the final py2 release and announce deprecation.

**Comment by om26er** [comment]
CI is fixed now (apart from py34-twtrunk), lets land this.

**Comment by oberstet** [comment]
ah pytest .. again;) anyways: cool that CI is all green.

**Comment by oberstet** [comment]
rgd release, yes, we should https://github.com/crossbario/txaio/pull/150

**Pull request merged**
