### PR TITLE
Create Future and Task objects of asyncio in the right way for python >= 3.4.2 

### PR DESCRIPTION
**Pull request by azazel75**
Hello, 

This PR checks alters aio.py to check the version of the running interpreter and if it's >= of 3.4.2  (3.5.2 for the futures) creates the Task and Future object in the right way, which is by calling `loop.create_task()` and `loop.create_future()` methods. This enables custom loop implementations to use the version of these objects that they are intended to use or, in the case of the Task, it correctly forwards the creation to the task factory configured by the user application. (see https://docs.python.org/3/library/asyncio-eventloop.html?highlight=create_future#asyncio.AbstractEventLoop.set_task_factory ).

This implements what proposed in #105 , which was closed for no good reason IMHO.

Incidentally I had to change the a pair of tests because the mock catches less method calls (but the test is correct anyway because the loop.create_* function gets called as expected) and found out that the reason for the missing catch is that now the speedup  (implemented in C) versions of Task and Future get instantiated instead of the less efficient counterparts implemented in Python, that was happening before this PR. This was confirmed by a manual inspection of the creation with pdb in cPython 3.6 where the Task and Future get created but the pdb is unable to step into the scheduling methods. **So probably this PR brings also some speedup**.

Finally, you may see the CI tests failing, but the only one failing is the `flake8` test but not on code involved by this PR.

### CODE REVIEW

**Comment by om26er** [comment]
@azazel75 could please resync with master, we just fixed the CI.

**Comment by azazel75** [comment]
@om26er I've merged with your master

**Comment by om26er** [comment]
> @om26er I've merged with your master

Thanks. Code looks good to me but would be better to have @oberstet opinion here.

**Comment by oberstet** [comment]
looks good (crossing fingers it'll work over all envs/versions;)

**Comment by meejah** [comment]
If it doesn't work on all platforms, it's because "not enough unit-tests" ;)

(Thanks for the PR, looks good!)

**Pull request merged**
