### PR TITLE
removed unnecessary logging handlers (#45)

### PR DESCRIPTION
**Pull request by WGH-**

### CODE REVIEW

**Comment by meejah** [comment]
This code was ported from autobahn, and although I agree it should probably be run in the ``start_logging`` method (not at import time) off the top of my head I don't know the ultimate purpose of this.

@hawkowl can you comment? (It came from bf324d7a5155606ccaada639c12c9e8808d27866 in autobahn-python ultimately...)

@WGH- I'm guessing you're not using the txaio logging "stuff"? (nor ``txaio.start_logging``?)

**Comment by WGH-** [comment]
No, I'm not.

**Comment by oberstet** [comment]
waiting for @hawkowl to comment ..

**Comment by oberstet** [comment]
@hawkowl maybe have a quick look and comment or close?

**Comment by hawkowl** [comment]
@oberstet I think @meejah may have a solution from the original bug report?

**Comment by oberstet** [comment]
I just noticed that you mentioned https://bitbucket.org/enovance/trollius/issues/19/no-handlers-could-be-found-for-logger in https://github.com/crossbario/txaio/issues/45, which seems to be @WGH- original itch.

**Comment by meejah** [comment]
This still needs manual testing against trollius to ensure we get logs at all after a ``start_logging()`` call -- my idea was that either we just apply this patch if that works fine, or perhaps we need to move the handler code into txaio's ``start_logging()`` when running under trollius...

The problem @WGH- is fixing is sort of the inverse: txaio is being rude and messing up "native" logging if you never call ``start_logging()``, but we need to confirm the other way -- that someone *not* starting their own logging and using just ``start_logging()`` gets logs printed...

**Comment by oberstet** [comment]
@meejah given the latest changes, can we close this?

**Comment by meejah** [comment]
@oberstet I don't think so -- I think we actually want to merge this; I'll test it though.

**Comment by meejah** [comment]
I tested that using trollius both with and without ``txaio.start_logging`` our logging works. Of course, if you don't call ``txaio.start_logging()`` you do have to start the stdlib logger yourself before getting any txaio API log-messages.

**Comment by meejah** [comment]
@WGH- thanks for the patch! Sorry I took so long to review it.

**Comment by WGH-** [comment]
It's cool, no worries.

**Pull request merged**
