### PR TITLE
batched call later

### PR DESCRIPTION
**Pull request by meejah**
Before merge, needs:

- [x]  release notes
- [x]  chunked notifications
- [x]  docs
- [x]  squashing

See #66

### CODE REVIEW

**Comment by meejah** [comment]
Okay, I think this is ready to merge -- with caveat that I haven't done very much testing for the "real" use-case in Autobahn (yet).

**Comment by oberstet** [comment]
Awesome!!

**Comment by oberstet** [comment]
I totally forgot about canceling .. nice, nice

**Comment by oberstet** [comment]
I do a release ..

**Comment by oberstet** [comment]
great:

```
creating build/bdist.linux-x86_64/wheel/txaio-2.4.0.dist-info/WHEEL
twine upload dist/*
Uploading distributions to https://pypi.python.org/pypi
Uploading txaio-2.4.0-py2.py3-none-any.whl
HTTPError: 500 Server Error: Internal Server Error for url: https://pypi.python.org/pypi
make: *** [publish] Fehler 1
```

**Comment by oberstet** [comment]
even greater:

```
creating build/bdist.linux-x86_64/wheel/txaio-2.4.0.dist-info/WHEEL
twine upload dist/*
Uploading distributions to https://pypi.python.org/pypi
Uploading txaio-2.4.0-py2.py3-none-any.whl
HTTPError: 400 Client Error: A file named "txaio-2.4.0-py2.py3-none-any.whl" already exists for  txaio-2.4.0. To fix problems with that file you should create a new release. for url: https://pypi.python.org/pypi
make: *** [publish] Fehler 1
```

**Comment by oberstet** [comment]
The wheel seem to have been published, but not the src dist: https://pypi.python.org/pypi/txaio/2.4.0

Oh, well. PyPI ..

**Comment by oberstet** [comment]
manually rebuilding only the src dist, and uploading only that:

```
copying setup.cfg -> txaio-2.4.0
Writing txaio-2.4.0/setup.cfg
creating dist
Creating tar archive
removing 'txaio-2.4.0' (and everything under it)
(cpy351_1) oberstet@corei7ub1310:~/scm/crossbario/txaio$ twine upload dist/*
Uploading distributions to https://pypi.python.org/pypi
Uploading txaio-2.4.0.tar.gz
HTTPError: 500 Server Error: Internal Server Error for url: https://pypi.python.org/pypi
(cpy351_1) oberstet@corei7ub1310:~/scm/crossbario/txaio$ ls -la dist/
insgesamt 52
drwxrwxr-x 2 oberstet oberstet  4096 Apr 22 10:05 .
drwxrwxr-x 9 oberstet oberstet  4096 Apr 22 10:05 ..
-rw-rw-r-- 1 oberstet oberstet 41359 Apr 22 10:05 txaio-2.4.0.tar.gz
(cpy351_1) oberstet@corei7ub1310:~/scm/crossbario/txaio$ twine upload dist/*
Uploading distributions to https://pypi.python.org/pypi
Uploading txaio-2.4.0.tar.gz
HTTPError: 400 Client Error: A file named "txaio-2.4.0.tar.gz" already exists for  txaio-2.4.0. To fix problems with that file you should create a new release. for url: https://pypi.python.org/pypi
(cpy351_1) oberstet@corei7ub1310:~/scm/crossbario/txaio$ 
```

But it's uploaded anyway. Strange.

**Pull request merged**
