### PR TITLE
remove obsolete dependency on six

### PR DESCRIPTION
**Pull request by a-detiste**

### CODE REVIEW

**Review by om26er — APPROVED** [review]
Makes sense. There is no usage of six throughout the library

```
om26er@RemotePC:~/scm/crossbario/txaio$ grep -r six
requirements.txt:six>=1.15.0
README.rst:This is like `six <http://pythonhosted.org/six/>`_, but for wrapping
```

**Comment by oberstet** [comment]
first of all, thanks for contributing! 

then, yes, this makes sense and it should be merged

for merging this desired change while at the same time stabilizing things and verify everything is still working (which it should of course as the change is purely technical), ideally I would like to rely on our CI

now, I had to acknowledge running the CI on your PR (which I had to do so only because this is your 1st contrib), the CI fails sadly - BUT this is not because of your change, but because GH actions, Python versions, PyPy and the cryptography package

short story long, the following change (only the 1st one) should be copy pasted into this PR:

https://github.com/crossbario/txaio/pull/185/files

once that is done, _this_ PR should run green, and if so, I'd merge it right away. if you or Omer could do that, would be a big help as I am occupied with other work. it should be easy. hopefully nothing else "unexpected" rgd CI pops up;) maintaining libraries in the presence of many OSS / SW pieces moving all the time is quite some work ..

**Review by oberstet — CHANGES_REQUESTED** [review]
pls see my comment in the PR thread

**Comment by om26er** [comment]
@a-detiste can you rebase your PR. the CI is fixed now.

**Comment by a-detiste** [comment]
Thank you very much for your time & consideration.

**Comment by oberstet** [comment]
the CI is green, cool, thanks for contributing! I am force merging as because of this unrelated GH workflow config issue https://github.com/crossbario/txaio/pull/187#issuecomment-1890134680 (not a CI issue) which in any case is completely unrelated to this change

**Pull request merged**
