### PR TITLE
Add namespace detection to aio make_logger

### PR DESCRIPTION
**Pull request by spr0cketeer**
This will bring AB aio logging namespace in line with the existing code on the tx side https://github.com/crossbario/txaio/blob/master/txaio/tx.py#L242 so all loggers returned from make_logger() calls will be in the 'autobahn.*' hierarchy.

A user's app level code can then configure log events from AB like:

```
ab_logger = logging.getLogger('autobahn')
ab_logger.setLevel(logging.INFO)
```

independently of the logging namespace used by the app:
```
myapp_logger = logging.getLogger(__name__)
myapp_logger.setLevel(logging.DEBUG)
```

Currently make_logger() calls always return the root logger.

### CODE REVIEW

**Comment by meejah** [comment]
This looks plausible -- but obviously some impacts on the unit-tests (at least); is this because those are only monitoring the root logger or something?

**Comment by oberstet** [comment]
no response from OP

**Comment by spr0cketeer** [comment]
Looks like there have been some commits changing how testing works since I submitted this PR - rebased on top of master and tests are running ok now.

This PR should fix this https://github.com/crossbario/autobahn-python/issues/952.

**Comment by spr0cketeer** [comment]
@oberstet can you reopen this please?  Not sure if you were confused about the timeline on this PR, but it didn't receive any attention for 3 months, then closed as I didn't reply to a question within 1 week - that's a little draconian!

**Comment by oberstet** [comment]
@spr0cketeer uups, sorry! I was indeed confused;) now, my practical problem is: the "Reopen" button is deactive . mmh. let me see what happens when I first comment ..

**Comment by oberstet** [comment]
so not sure: the button just is not there, means, I can carry over the changes manually, but that looses authorship - or @spr0cketeer you reopen from your side. sorry! let me know ..

**Comment by spr0cketeer** [comment]
@oberstet I rebased and force pushed so maybe that's why the Reopen button is disabled? 

Following the example in this: https://gist.github.com/robertpainsi/2c42c15f1ce6dab03a0675348edd4e2c

I've now done step 3 and force pushed back to the commit when this PR was closed - is the Reopen button enabled now?  If not I'll just resubmit a new PR.

**Comment by oberstet** [comment]
@spr0cketeer cool, whatever you did worked (I could reopen the PR;) thanks

**Comment by oberstet** [comment]
@meejah could you have a look into this? I really can't say much .. quite cryptic;)

**Comment by meejah** [comment]
The code looks good to me. I haven't tested it yet and would like to at least know what effect this has on Autobahn logging messages -- I'm pretty sure the effect is good: instead of all logs going to the root logger they'll have a more-proper namespace.

Ideally we'd have an explicit test for the namespace, too. I wouldn't hold up merging for this though.

But, we should probably put that in the next Autobahn release-notes?

**Comment by spr0cketeer** [comment]
This change will allow `component.start()` users to control the output location and format of AB's logs as all AB loggers will be under the autobahn.* namespace.  AB does not call txaio's `start_logging()` using this method, so no output handlers or log format is set.

`run([components])` and `ApplicationRunner.run(ApplicationSession`) both call `start_logging()`. This attaches a handler to the root logger with a log format string which doesn't include the (now namespaced) logger name, so they will see no difference to the output format of AB's log messages.

However it will not fix the problems inherent to `start_logging()`'s use of the root logger e.g https://github.com/crossbario/autobahn-python/issues/952 - this would require some changes to the way `start_logging()` works, with any changes requiring this PR be in place first.

**Pull request merged**
